name: Xcodebuild Action
description: Runs xcodebuild e.g. to run tests.
author: ser.soft GmbH
inputs:
  workspace:
    description: The path to the xcworkspace to build. Mutually exclusive with `project` and `spm-package`. See also `xcodebuild`'s `-workspace`.
    required: false
  project:
    description: The path to the xcodeproj to build. Mutually exclusive with `workspace` and `spm-package`. See also `xcodebuild`'s `-project`.
    required: false
  spm-package:
    description: The path to the SPM package (folder containing Package.swift) to build. Mutually exclusive with `workspace` and `project`.
    required: false
  scheme:
    description: The scheme to build. Required when using a workspace. See also `xcodebuild`'s `-scheme`.
    required: false
  target:
    description: The target to build. See also `xcodebuild`'s `-target`.
    required: false
  all-targets:
    description: If `true`, all targets will be built. See also `xcodebuild`'s `-allTargets`.
    required: false
  destination:
    description: The destination specifier to build. See also `xcodebuild`'s `-destination`.
    required: false
  configuration:
    description: The configuration to build. See also `xcodebuild`'s `-configuration`.
    required: false
  sdk:
    description: The SDK to use for building. See also `xcodebuild`'s `-sdk`.
    required: false
  arch:
    description: The architecture to use for building. See also `xcodebuild`'s `-arch`.
    required: false
  xcconfig:
    description: The path to an xcconfig file with build settings overrides. See also `xcodebuild`'s `-xcconfig`.
    required: false
  toolchain:
    description: The toolchain identifier or name to use for building. See also `xcodebuild`'s `-toolchain`.
    required: false
  jobs:
    description: The number of jobs to use for building. See also `xcodebuild`'s `-jobs`.
    required: false
  parallelize-targets:
    description: If `true`, the targets will be built in parallel. See also `xcodebuild`'s `-parallelizeTargets`.
    required: false
  enable-code-coverage:
    description: If `true`, code coverage is enabled while testing. See also `xcodebuild`'s `-enableCodeCoverage`.
    required: false
  parallel-testing-enabled:
    description: If `true`, tests are executed in parallel. See also `xcodebuild`'s `-parallel-testing-enabled`.
    required: false
  maximum-concurrent-test-device-destinations:
    description: The maximum number of device destinations to run in parallel. See also `xcodebuild`'s `-maximum-concurrent-test-device-destinations`.
    required: false
  maximum-concurrent-test-simulator-destinations:
    description: The maximum number of simulator destinations to run in parallel. See also `xcodebuild`'s `-maximum-concurrent-test-simulator-destinations`.
    required: false
  quiet:
    description: If `true`, xcodebuild won't print anything except warnings and errors. See also `xcodebuild`'s `-quiet`.
    required: false
  hide-shell-script-environment:
    description: If `true`, xcodebuild won't print the environment for shell build scripts. See also `xcodebuild`'s `-hideShellScriptEnvironment`.
    required: false
  enable-address-sanitizer:
    description: Whether the address sanitizer should be enabled. See also `xcodebuild`'s `-enableAddressSanitizer`.
    required: false
  enable-thread-sanitizer:
    description: Whether the thread sanitizer should be enabled. See also `xcodebuild`'s `-enableThreadSanitizer`.
    required: false
  enable-undefined-behavior-sanitizer:
    description: Whether the undefined behavior sanitizer should be enabled. See also `xcodebuild`'s `-enableUndefinedBehaviorSanitizer`.
    required: false
  result-bundle-path:
    description: The path that should be used for the result bundle. See also `xcodebuild`'s `-resultBundlePath`.
    required: false
  result-bundle-version:
    description: The version that should be used for the result bundle. See also `xcodebuild`'s `-resultBundleVersion`.
    required: false
  cloned-source-packages-path:
    description: The path that should be used for the cloning of remote packages. See also `xcodebuild`'s `-clonedSourcePackagesDirPath`.
    required: false
  package-cache-path:
    description: The path of caches used for package support. See also `xcodebuild`'s `-packageCachePath`.
    required: false
  derived-data-path:
    description: The path that should be used for derived data. See also `xcodebuild`'s `-derivedDataPath`.
    required: false
  default-package-registry-url:
    description: The default package registry URL. See also `xcodebuild`'s `-defaultPackageRegistryURL`.
    required: false
  package-dependency-scm-to-registry-transformation:
    description: The package dependency SCM to registry transformation. See also `xcodebuild`'s `-packageDependencySCMToRegistryTransformation`.
    required: false
  disable-package-repository-cache:
    description: Whether the package repository cache should be disabled. See also `xcodebuild`'s `-disablePackageRepositoryCache`.
    required: false
  disable-automatic-package-resolution:
    description: Whether automatic package resolution should be disabled. See also `xcodebuild`'s `-disableAutomaticPackageResolution`.
    required: false
  skip-package-updates:
    description: Whether package updates should be skipped. See also `xcodebuild`'s `-skipPackageUpdates`.
    required: false
  skip-package-plugin-validation:
    description: Whether package plugin validation should be skipped. See also `xcodebuild`'s `-skipPackagePluginValidation`.
    required: false
  skip-macro-validation:
    description: Whether macro validation should be skipped. See also `xcodebuild`'s `-skipMacroValidation`.
    required: false
  package-fingerprint-policy:
    description: The package fingerprint checking policy. See also `xcodebuild`'s `-packageFingerprintPolicy`.
    required: false
  package-signing-entity-policy:
    description: The package signing entity policy. See also `xcodebuild`'s `-packageSigningEntityPolicy`.
    required: false
  xcroot:
    description: The path to a .xcroot to use for building and/or testing. See also `xcodebuild`'s `-xcroot`.
    required: false
  xctestrun:
    description: The path to a test run specification. See also `xcodebuild`'s `-xctestrun`.
    required: false
  test-language:
    description: The language to use for testing. See also `xcodebuild`'s `-testLanguage`.
    required: false
  test-region:
    description: The region to use for testing. See also `xcodebuild`'s `-testRegion`.
    required: false
  test-plan:
    description: The name of the test plan associated with the scheme to use for testing. See also `xcodebuild`'s `-testPlan`.
    required: false
  only-testing:
    description: A (line-separated) list of tests to run. See also `xcodebuild`'s `-only-testing`.
    required: false
  skip-testing:
    description: A (line-separated) list of tests to skip. See also `xcodebuild`'s `-skip-testing`.
    required: false
  only-test-configuration:
    description: A (line-separated) list of test configurations to run. See also `xcodebuild`'s `-only-test-configuration`.
    required: false
  skip-test-configuration:
    description: A (line-separated) list of test configurations to skip. See also `xcodebuild`'s `-skip-test-configuration`.
    required: false
  test-iterations:
    description: The number of iterations to run the tests. See also `xcodebuild`'s `-test-iterations`.
    required: false
  retry-tests-on-failure:
    description: Whether tests should be retried on failure. See also `xcodebuild`'s `-retry-tests-on-failure`.
    required: false
  run-tests-until-failure:
    description: Whether tests should be run until failure. See also `xcodebuild`'s `-run-tests-until-failure`.
    required: false
  skip-unavailable-actions:
    description: Whether unavailable actions should be skipped instead of failing the execution. See also `xcodebuild`'s `-skipUnavailableActions`.
    required: false
  allow-provisioning-updates:
    description: Whether provisioning updates are allowed. See also `xcodebuild`'s `-allowProvisioningUpdates`.
    required: false
  allow-provisioning-device-registration:
    description: Whether provisioning device registrations are allowed. See also `xcodebuild`'s `-allowProvisioningDeviceRegistration`.
    required: false
  export-notarized-app:
    description: Whether the app should be exported notarized. See also `xcodebuild`'s `-exportNotarizedApp`.
    required: false
  export-options-plist:
    description: The path to an export options plist. See also `xcodebuild`'s `-exportOptionsPlist`.
    required: false
  export-archive:
    description: Whether an archive should be exported. See also `xcodebuild`'s `-exportArchive`.
    required: false
  archive-path:
    description: The path to where archives are created. See also `xcodebuild`'s `-archivePath`.
    required: false
  create-xcframework:
    description: Whether an xcframework should be created. See also `xcodebuild`'s `-create-xcframework`.
    required: false
  build-settings:
    description: Arbitrary, space separated build settings (e.g. PLATFORM_NAME=iphonesimulator).
    required: false
  action:
    description: The action to perform (e.g. build, test, ...). Can also contain multiple actions.
    required: true
    default: test
  output-formatter:
    description: The output formatter to use (e.g. xcpretty, xcbeautify, ...). The xcodebuild output will be piped into this formatter.
    required: false
    default: 'xcpretty --color'
  disable-enum-input-validation:
    description: Whether the input validation for enums should be disabled. Usually only needed if new values are added to the enums in the future.
    required: false
    default: 'false'
  dry-run:
    description: '<TEST ONLY> Whether the commands should only be composed and not actually run. Only used in test.'
    required: false
outputs:
  unprocessed-command:
    description: The unprocessed command from which the executed command was resolved. E.g. paths are not resolved in this one.
  executed-command:
    description: The command that was executed.
runs:
  using: node20
  main: dist/index.js
branding:
  color: blue
  icon: check-square
