name: Xcodebuild Action
description: Runs xcodebuild e.g. to run tests.
author: ser.soft GmbH
inputs:
  workspace:
    description: The path to the xcworkspace to build. Mutually exclusive with `project`.
    required: false
  project:
    description: The path to the xcodeproj to build. Mutually exclusive with `workspace`.
    required: false
  scheme:
    description: The scheme to build. Required when using a workspace.
    required: false
  destination:
    description: The destination specifier to build.
    required: false
  configuration:
    description: The configuration to build.
    required: false
  sdk:
    description: The SDK to use for building.
    required: false
  skip-testing:
    description: A list of tests to skip.
    required: false
  derived-data-path:
    description: Override the folder that should be used for derived data
    required: false
  build-settings:
    description: Arbitrary, space separated build settings (e.g. PLATFORM_NAME=iphonesimulator).
    required: false
  action:
    description: The action to perform (e.g. build, test, ...).
    required: true
    default: test
  use-xcpretty:
    description: Whether the output of xcodebuild should be forwarded to xcpretty.
    required: true
    default: true
  dry-run:
    description: '[TEST ONLY]: Whether the commands should only be printed but not actually run. Only used in test.'
    required: false
runs:
  using: node12
  main: dist/index.js
branding:
  color: blue
  icon: check-square
