#if !canImport(ObjectiveC)
import XCTest

extension TestPackageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestPackageTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TestPackageTests.__allTests__TestPackageTests),
    ]
}
#endif
